<?php

/**
 * Prepares variables for the page template.
 *
 * Default template: page.html.twig.
 *
 * See the page.html.twig template for the list of variables.
 */
function school_preprocess_page(&$variables) {
  $stop_xdebug = "DELETE THIS LINE - THIS LINE NEEDS FOR X-DEBUG";
}

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 */
function school_preprocess_html(&$variables) {
  $stop_xdebug = "DELETE THIS LINE - THIS LINE NEEDS FOR X-DEBUG";
}
